<a href="https://colab.research.google.com/github/TAKE-JP-17/Pytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

LISTS

In [1]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

NUMPY ARRAYS

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.44993838, 0.6381105 , 0.6366511 , 0.03659647],
       [0.7135037 , 0.72697199, 0.65983544, 0.87247571],
       [0.4671238 , 0.71957456, 0.10694481, 0.39320623]])

In [5]:
np1.dtype

dtype('float64')

TENSORS

In [9]:
tensor_2d = torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [7]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4499, 0.6381, 0.6367, 0.0366],
        [0.7135, 0.7270, 0.6598, 0.8725],
        [0.4671, 0.7196, 0.1069, 0.3932]], dtype=torch.float64)