<a href="https://colab.research.google.com/github/TAKE-JP-17/Pytorch/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [4]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [5]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [6]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [7]:
# Sub Function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [8]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [9]:
# Mul longhand
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [10]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [11]:
# Div Longhand
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [12]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [13]:
# Remainder Longhand
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [14]:
# Exponents / power
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [15]:
# Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [16]:
# Reassignment_
tensor_a+tensor_b

tensor([ 6,  8, 10, 12])

In [19]:
tensor_a

tensor([1, 2, 3, 4])

In [21]:
# tensor_a=tensor_a+tensor_b
tensor_a.add_(tensor_b)

tensor([11, 14, 17, 20])

In [22]:
tensor_a

tensor([11, 14, 17, 20])